version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aozerov
      POSTGRES_PASSWORD: '0112'
    ports:
      - "5433:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  ms:
    image: practice-rs:ms
    environment:
      MS_ADDR: MS_ADDR=0.0.0.0:3000
      DATABASE_URL: postgres://aozerov:0112@db:5432/echo_ms
    ports:
      - "3001:3000"
    depends_on:
      - db