version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aozerov
      POSTGRES_PASSWORD: '0112'
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data